### ISSUE TITLE
set operation

### ISSUE THREAD

**Issue by ndunello** [MahdadGhasemian/node-network-manager#6]
Sorry, I didn't understand if it is possible to **set** the configuration or it's only possible to **get**.
Is it possible, for example, set fixed IP address for the first ethernet interface ?
If so, can you show an example ?

**Comment by MahdadGhasemian** [comment]
Hi @ndunello 

I've just added some new functions to cover your requirement for adding a new connection with static IP. (Version 1.0.14)
You can create a new connection with your desired IP (static) and then switch on with up command.
example:

```
// create new connection with static ip and gateway
network
    .addEthernetConnection(connectionName, "enp0s3", ip, "192.168.1.1")
    .then(() => {
        // edit its dns
        network
            .changeDnsConnection(connectionName, "8.8.8.8 8.8.4.4").then(() => {
                // connection up
                network
                    .connectionUp(connectionName)

            })
    })
```
